eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9030
spring:
  application:
    name: zuulservice
  datasource:
    url: jdbc:mysql://47.93.193.177:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
        
zuul:
  routes:
    #userservice:
      #path: /user/**
      #strPrefix: true    # true 取消/user/ 
      #url: http://localhost:9001/user
      
      #strPrefix: false    # false /user/ 
      #url: http://localhost:9001
    #feignservice:
      #path: /org/**
      #strPrefix: true
      #url: http://localhost:9002/org
      #serviceId: feignservice
    debug:
      request: true      

#这里的配置表示，访问/baidu/** 直接重定向到http://www.baidu.com
#zuul.routes.baidu.path=/baidu/**
#zuul.routes.baidu.url=http://www.baidu.com

#反响代理配置
#这里的配置类似nginx的反响代理
#当请求/api/**会直接交给listOfServers配置的服务器处理
#当stripPrefix=true的时候 （http://127.0.0.1:8181/api/user/list -> http://192.168.1.100:8080/user/list）
#当stripPrefix=false的时候（http://127.0.0.1:8181/api/user/list -> http://192.168.1.100:8080/api/user/list）
#zuul.routes.api.path=/api/**
#zuul.routes.api.stripPrefix=false
#api.ribbon.listOfServers=192.168.1.100:8080,192.168.1.101:8080,192.168.1.102:8080

#url重写配置
#这里的配置，相当于访问/index/** 会直接渲染/home的请求内容(和直接请求/home效果一样), url地址不变
#zuul.routes.index.path=/index/**
#zuul.routes.index.url=forward:/home